export const ACCOUNTS_PAGES = {
  IMPORT_TAB: 'import_tab',
  NEW_ACCOUNT: 'new_account',
  SAVE_BACKUP: 'safe_backup',
  CONFIRM_BACKUP: 'confirm_backup',
  IMPORT_DEBUG: 'import_debug',
  IMPORT_SEED: 'import_seed',
  IMPORT_LEDGER: 'import_ledger',
  IMPORT_KEYSTORE: 'import_keystore',
  IMPORT_EMAIL: 'import_email',
  ACCOUNT_NAME: 'account_name',
  IMPORT_SUCCESS: 'import_success',
  IMPORT_SUCCESS_KEYSTORE: 'import_success_keystore',
  IMPORT_ADDRESS_BOOK: 'import_address_book',
  IMPORT_SUCCESS_ADDRESS_BOOK: 'import_success_address_book',
  WELCOME: 'welcome',
  NEW: 'new',
  FORGOT: 'forgot_password',
};
