export const ACCOUNTS_PAGES = {
  HOME: '/',
  NEW_ACCOUNT: '/create-account',
  SAVE_BACKUP: '/create-account/save-backup',
  CONFIRM_BACKUP: '/create-account/confirm-backup',
  IMPORT_DEBUG: '/import-debug',
  IMPORT_SEED: '/import-seed',
  IMPORT_LEDGER: '/import-ledger',
  IMPORT_KEYSTORE: '/import-keystore',
  IMPORT_SUCCESS_KEYSTORE: '/import-keystore/success',
  IMPORT_EMAIL: '/import-email',
  ACCOUNT_NAME: '/account-name',
  IMPORT_SUCCESS: '/import-success',
  IMPORT_ADDRESS_BOOK: '/import-address-book',
  IMPORT_SUCCESS_ADDRESS_BOOK: '/import-address-book/success',
  NEW: '/init-vault',
  FORGOT: '/forgot-password',
};
