name: Pull migrations
on: create

jobs:
  pull-migrations:
    if: ${{ contains(github.ref, 'rollback-release-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extractBranch

      - name: Pull migrations
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin master
          git checkout origin/master -- src/storage/migrations.ts
          git add src/storage/migrations.ts
          git commit -m "Pull migrations"
          git push origin HEAD:${{ steps.extractBranch.outputs.branch }}
