name: Release
on:
  release:
    types: [published]
jobs:
  report:
    runs-on: self-hosted
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: Keeper-Wallet/jira-action@v1
        with:
          component: ext
          hooks-url: ${{ secrets.HOOKS_URL }}
          hook-release: ${{ secrets.HOOK_RELEASE }}
