name: Jira test
on:
  push:
    branches-ignore:
      - master
jobs:
  report:
    runs-on: self-hosted
    steps:
      - run: curl -4 icanhazip.com
      - run: curl https://jira.wavesplatform.com/secure/Dashboard.jspa --fail -I

